---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by klook.
--- DateTime: 2020/6/3 下午7:20
---

local function set_header(key)
    return key
end


local _M = {}
_M.__index = _M

function _M:new(token)
    if type(token) ~= "string" then
        error("Token must be a string, got " .. tostring(token), 2)
    end

    local token, err = decode_token(token)
    if err then
        return nil, err
    end

    return setmetatable(token, _M)
end

function _M:set_header(input)
    return set_header(input)
end

return _M